#ifndef __SIMULATOR_CONFIGS_H__
#define __SIMULATOR_CONFIGS_H__

#ifndef CONSOLE_DEBUG_LEVEL
#define CONSOLE_DEBUG_LEVEL CONSOLE_DEBUG_LEVEL_INFO
#endif

#ifndef CONSOLE_DEBUG_ANSI_COLOR_ENABLE
#define CONSOLE_DEBUG_ANSI_COLOR_ENABLE 1
#endif

#endif /* __SIMULATOR_CONFIGS_H__ */